# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxx
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxx

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "If2/l7XGr6izTVPZRWubEEFWarm7/wte3zfk/MqZn9kz94Dw8ikaLx5jyUhLpM4hoJbxqMEd01tNJBCJrfVmrQ1kdOeq1RJ8omlU5k9jkRSLEE1AV0/HYjfd6D7/h8y1LmNl1F6dlX06F5zo5rcoCc0nldM3faYDX0VH2jqQn1HHjziZBS8JpAB0OS3wUX1+uXIKGj9jRqCRIOKm/pcVCOtwRNoSOSwxd/wLxaxHzeMGc96BWA6Vvj5wOBZgGIDoeY8K5JRu/Wf2UeLFrI7tBjSizgQxNGDRkOuG+UCiyz0+b0BlPTnnYIdo2TdbcXCl+0ubUiWU0hhyzKhZiy6vulT1aScfTZszoNzRmMjLin+4Zeruj3Ekcl8aHLwTX2vZOSxgb418EH2Hz3gKMPMXdDKkP5yXiDLnznxF4QvS8u8UA/003EHuGbNlL8P5Szf7ppg2ZGygQMEH1F+YXzkRkiYz4YjzUDkE+dUWRBDMjHkUejFESLuvJ3OfzzYH5d3Q0unOo5d/JA6XmMV8Fie67wdy+7Y77EVIpk1RxJCeqc5odK1RlJ4U/99zmt6TAdtMN5dqivHg/NPhB+Ie6Y0RP7xWWMulpLysWNnPHWpi/SEvo2okWMh21AoHdLL3cvw5IsYwEJrZcrckh32neRcwGwJ+iTj2A6z9jxc9J+8lrlY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
